name: Crypto Arbitrage Monitor

on:
  schedule:
    - cron: '*/15 * * * *'  # Run every 15 minutes
  workflow_dispatch:  # Allow manual trigger

jobs:
  check-arbitrage:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ccxt pandas python-telegram-bot numpy
    
    - name: Create config directory and file
      run: |
        mkdir -p config
        echo "[Bitget]" > config/config.ini
        echo "api_key=${{ secrets.BITGET_API_KEY }}" >> config/config.ini
        echo "secret_key=${{ secrets.BITGET_SECRET_KEY }}" >> config/config.ini
        echo "passphrase=${{ secrets.BITGET_PASSPHRASE }}" >> config/config.ini
        echo "[MEXC]" >> config/config.ini
        echo "api_key=${{ secrets.MEXC_API_KEY }}" >> config/config.ini
        echo "secret_key=${{ secrets.MEXC_SECRET_KEY }}" >> config/config.ini
        
    - name: Test Telegram Notification
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        echo "Testing Telegram notification..."
        python -m src.test_notification
        
    - name: Run arbitrage scanner
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python -m src.trading
