# .github/workflows/arbitrage-scanner.yml
name: Arbitrage Scanner

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ccxt pandas python-telegram-bot requests
        
    - name: Create config directory
      run: |
        mkdir -p config
        
    - name: Create config file
      run: |
        echo "[Bitget]" > config/config.ini
        echo "api_key=${{ secrets.BITGET_API_KEY }}" >> config/config.ini
        echo "secret_key=${{ secrets.BITGET_SECRET_KEY }}" >> config/config.ini
        echo "passphrase=${{ secrets.BITGET_PASSPHRASE }}" >> config/config.ini
        echo "" >> config/config.ini
        echo "[MEXC]" >> config/config.ini
        echo "api_key=${{ secrets.MEXC_API_KEY }}" >> config/config.ini
        echo "secret_key=${{ secrets.MEXC_SECRET_KEY }}" >> config/config.ini
        echo "" >> config/config.ini
        echo "[Telegram]" >> config/config.ini
        echo "bot_token=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> config/config.ini
        echo "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" >> config/config.ini
        
    - name: List directory contents
      run: |
        ls -la
        
    - name: Run arbitrage scanner
      run: |
        python Arbitrage/trading.py
